### ISSUE TITLE
Wrong place for PULL_REQUEST_TEMPLATE.md 

### ISSUE THREAD

**Issue by jibe0123** [qraimbault/vue-js-starter-scss#105]
**Describe the bug**
Template for PR isn't available 

**Expected behavior**
When you want to suggest a PR, no template

**Comment by qraimbault** [comment]
Looks like you talk about the issues templates. 

The pull request template is working and placed at the right place (see https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)
